version: '3.8'
services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules/ # Change to make sure node_modules is properly handled
    command: ["npm", "start"] # Add this line to ensure that npm start runs the app after container starts
